name: Project Build, Test, & Deploy

on:
  push:
    branches: ["main", "develop", "testing"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Build with Maven
        run: mvn clean package

      - uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: "target/*.jar"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Run tests and verify
        run: mvn verify

      - name: Generate Jacoco Report
        run: mvn jacoco:report

      - uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: "target/site/jacoco/"
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Desplegar a Railway
        run: |
          echo "Desplegando en Railway..."
          if [ "${{ github.ref_name }}" = "Develop" ]; then
            RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN_STAGING }} railway up --service TROYA_STATISTICS_SUSTAINABILITY_BACKEND --environment Staging
          elif [ "${{ github.ref_name }}" = "main" ]; then
            RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN_PRODUCTION }} railway up --service TROYA_STATISTICS_SUSTAINABILITY_BACKEND --environment production
          fi

     
